# Generated by Django 5.1.3 on 2024-12-03 16:27

import django.utils.timezone
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("memorandum", "Memorandum"),
                            ("hoa", "HOA"),
                            (
                                "documented procedures manual",
                                "Documented Procedures Manual",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("number_pages", models.IntegerField()),
                ("ocr_metadata", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(upload_to=documents.models.Document.upload_to),
                ),
                (
                    "date_uploaded",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
