# Generated by Django 5.1.3 on 2024-11-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="metadata",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[("memorandum", "Memorandum"), ("hoa", "HOA")], max_length=32
            ),
        ),
    ]
