# Generated by Django 5.1.3 on 2024-11-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_metadata_alter_document_document_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="metadata",
        ),
        migrations.AddField(
            model_name="document",
            name="ocr_metadata",
            field=models.TextField(blank=True, null=True),
        ),
    ]
