# Generated by Django 5.1.3 on 2024-11-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_remove_document_metadata_document_ocr_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("memorandum", "Memorandum"),
                    ("hoa", "HOA"),
                    ("documented procedures manual", "Documented Procedures Manual"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
