# Generated by Django 5.1.3 on 2025-01-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_memorandum_from"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="memorandum_from",
            new_name="sent_from",
        ),
    ]
