# Generated by Django 5.1.3 on 2025-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_rename_memorandum_from_document_sent_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_month",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="document_year",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="subject",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
