# Generated by Django 5.1.3 on 2025-01-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization_requests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorizationrequest",
            name="documents",
        ),
        migrations.AlterField(
            model_name="authorizationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("claimed", "Claimed"),
                    ("unclaimed", "Unclaimed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AuthorizationRequestUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.TextField(max_length=256)),
                ("copies", models.IntegerField(default=1)),
                (
                    "authorization_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authorization_requests.authorizationrequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authorizationrequest",
            name="documents",
            field=models.ManyToManyField(
                to="authorization_requests.authorizationrequestunit"
            ),
        ),
    ]
