# Generated by Django 5.1.3 on 2025-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization_requests",
            "0002_remove_authorizationrequest_documents_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationrequestunit",
            name="pages",
            field=models.IntegerField(default=1),
        ),
    ]
