# Generated by Django 5.1.3 on 2025-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization_requests", "0003_authorizationrequestunit_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizationrequestunit",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("checked", "Checked")],
                default="pending",
                max_length=32,
            ),
        ),
    ]
