# Generated by Django 5.1.3 on 2024-12-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_requests", "0001_initial"),
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequest",
            name="questionnaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questionnaires.questionnaire",
            ),
        ),
    ]
