# Generated by Django 5.1.3 on 2025-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_requests", "0002_documentrequest_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequest",
            name="denied_remarks",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
