# Generated by Django 5.1.3 on 2025-01-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_requests", "0003_documentrequest_denied_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentrequest",
            old_name="denied_remarks",
            new_name="remarks",
        ),
    ]
