# Generated by Django 5.1.3 on 2025-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_requests", "0004_rename_denied_remarks_documentrequest_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("claimed", "Claimed"),
                    ("unclaimed", "Unclaimed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
