# Generated by Django 5.1.3 on 2024-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd0_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd1_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd2_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd3_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd4_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd5_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd6_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd7_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="sqd8_answer",
            field=models.CharField(
                choices=[
                    ("1", "Strongly Disagree"),
                    ("2", "Disagree"),
                    ("3", "Neither Agree nor Disagree"),
                    ("4", "Agree"),
                    ("5", "Strongly Agree"),
                    ("6", "N/A"),
                ],
                max_length=16,
            ),
        ),
    ]
