# Generated by Django 5.1.3 on 2025-01-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning")],
                default="info",
                max_length=16,
            ),
        ),
    ]
